/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp service_interface.xml -a service_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "service_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServiceAdaptor
 */

ServiceAdaptor::ServiceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServiceAdaptor::~ServiceAdaptor()
{
    // destructor
}

int ServiceAdaptor::value() const
{
    // get the value of property value
    return qvariant_cast< int >(parent()->property("value"));
}

int ServiceAdaptor::lart(int v)
{
    // handle method call org.realxtend.Test.Service.lart
    int out0;
    QMetaObject::invokeMethod(parent(), "lart", Q_RETURN_ARG(int, out0), Q_ARG(int, v));
    return out0;
}

