/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp service_interface.xml -a service_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVICE_ADAPTOR_H_1249387750
#define SERVICE_ADAPTOR_H_1249387750

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.realxtend.Test.Service
 */
class ServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.realxtend.Test.Service")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.realxtend.Test.Service\" >\n"
"    <property access=\"read\" type=\"i\" name=\"value\" />\n"
"    <method name=\"lart\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"v\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ServiceAdaptor(QObject *parent);
    virtual ~ServiceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(int value READ value)
    int value() const;

public Q_SLOTS: // METHODS
    int lart(int v);
Q_SIGNALS: // SIGNALS
};

#endif
