/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp entity_interface.xml -a entity_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "entity_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class EntityAdaptor
 */

EntityAdaptor::EntityAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

EntityAdaptor::~EntityAdaptor()
{
    // destructor
}

QString EntityAdaptor::component() const
{
    // get the value of property component
    return qvariant_cast< QString >(parent()->property("component"));
}

void EntityAdaptor::setComponent(const QString &value)
{
    // set the value of property component
    parent()->setProperty("component", qVariantFromValue(value));
}

void EntityAdaptor::go_nuts()
{
    // handle method call org.realxtend.Test.Entity.go_nuts
    QMetaObject::invokeMethod(parent(), "go_nuts");
}

